Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
DataBase:
  DBType: mysql
  Username: root
  Password: 12345678
  Host: 127.0.0.1:3306
  DBName: go_week02_blog
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
